### ISSUE TITLE
Clarification on error_threshold in Approximate Compilation

### ISSUE THREAD

**Issue by TeWas** [BQSKit/bqskit-tutorial#5]
I'm currently working through the `1_compiling_with_bqskit` tutorial, specifically the section on Approximate Compilation and Verification. In the tutorial, it states that the compiler will calculate the maximum `delta` and record a warning if it is greater than the `error_threshold`.

I'm seeking clarification on the following:

Does the error_threshold (or the computed value mentioned in the warning) represent:

1. The upper bound and thus the sum of all `epsilon_i` ​values, or
2. The maximum value among the individual `epsilon_i` values?

Thank you in advance for your help!

**Comment by edyounis** [comment]
The upper bound of the error across the entire compilation. Let me know if you have any more questions
